### ISSUE TITLE
docker gid can be different to host

### ISSUE THREAD

**Issue by ajtucker** [Shimmi/docker-jenkins#3]
Hi,

While I've had this working ok, a recent reboot of my host ended with the host having a different gid for the docker group (233) than that created in the container (999), so I had to resort to `chgrp 999 /var/run/docker.sock` on my host so that Jenkins has permission to access the socket.

I've tried using the 'group_add: docker' option in my docker-compose file, but this doesn't seem to change the gid of the docker group in the running container. Maybe because the group is already created in the container?

How do others cope with this?

Alex.

**Comment by colonelpopcorn** [comment]
I was under the impression that groups and everything would already be setup inside the container. However, I have yet to successfully complete a docker job with this container. Maybe if we were able to pass the gid on the host to the container as an environment variable and create the group from that?

Edit: I tried setting up a build argument in the Dockerfile to manually specify the gid of the docker group. The problem is that it's likely the gid of the docker group on your host is already allocated inside the container. For example, my default docker-machine on windows has a docker group gid of 100. I did confirm that changing ownership of the docker socket worked. I was also still able to spin up containers from outside the Jenkins container. It sucks, though, because the dream of spinning up a Jenkins container and immediately begin creating more containers for builds is too good to pass up. Any ideas to get this permission issue settled? How does docker handle groups if they're already created?

**Comment by Shimmi** [comment]
Hi guys,
Truly sorry for late response. I've had no time to investigate it at the start and then forget about it.

The fact that the GID of the docker group changed after the restart seems pretty weird to me. Once the group/user is created in the system, they are persistent and their GID/UID shall not change after rebooting.

Different docker group IDs shall be solvable either via the `--group-add docker` parameter when using the `run` command or adding `group_add: \n - docker` to the `docker-compose`. Just make sure your docker socket is set to docker group `ls -la /var/run/docker.sock`.

Please, take a look at the https://github.com/jenkinsci/docker/issues/263. This could add you some info.

**Comment by colonelpopcorn** [comment]
I was having this issue on a BusyBox based VM. A BusyBox VM's docker GID is something like 99, but your Docker image's GID is 999. I haven't figured out a way to change this at build time or run time, and docker builds won't complete without access to the docker socket. Which I can't achieve unless I change the group owner of the docker socket on the VM to GID 999 instead of GID 99. My next step is to move from a BusyBox based VM to a Debian based VM. Maybe that will help? 🤷‍♂️
