### ISSUE TITLE
dial unix /var/run/docker.sock: connect: permission denied

### ISSUE THREAD

**Issue by chafey** [Shimmi/docker-jenkins#4]
I get the above error when trying do use docker from my Jenkinsfile.  If I run the jenkins process as root, it works fine.  I am not sure what the right fix is - change permission on /var/run/docker.sock, run jenkins as root or some other change.

**Comment by Shimmi** [comment]
Hi @chafey,
As you correctly pointed out, this is because Jenkins lacks permissions to access the socket to communicate with the Docker engine. You basically need to add Jenkins user to the docker group (`usermod -a -G docker jenkins`). Yet this can be a bit tricky due to mixing GID/UID of host and guest OS (as mentioned in #3).

You may run the Jenkins as a root, but please be aware this is not recommended and can be insecure, but can be sufficient for testing and personal set-up.

Please take a look e.g. at this issue for more info https://github.com/jenkinsci/docker/issues/263.
